import os
import click
import shutil

from dlhub_cli.printing import format_output
from dlhub_cli.parsing import dlhub_cmd

# Path of this
template_path = os.path.join(os.path.dirname(__file__), 'init_templates')


@dlhub_cmd('init', help='Initialize a DLHub servable.'
                        ' Creates a Python script to generate model description from a template.')
@click.option('--force', is_flag=True,
              help='Whether to overwrite an existing file')
@click.option('--name', default="describe_model.py",
              help='Name of the Python script generated by init')
def init_cmd(force, name):
    """
    Initial step in creating a DLHub model.

    Creates a Python script that a user can edit to create a description for an artifact

    Args:
        force (bool): Whether to overwrite an existing template file
        name (string): Name of the template file to create
    """

    format_output("Initializing")

    # Check if a file would be overwritten
    if os.path.isfile(name) and not force:
        format_output("There is already a file named '{}'. Use --force to overwrite".format(name))
        return 1

    # Copy the template to the directory
    shutil.copy(os.path.join(template_path, 'describe_model.py'), name)
